version: 0.2

phases:
  install:
    commands:
      - npm ci
  build:
    commands:
      - npm run build
artifacts:
  files:
    - "**/*" # Include all files
  exclude-files:
    - node_modules/** # Exclude unnecessary files
    - .git/** # Exclude Git files
    - .next/cache/** # Exclude Next.js cache
  base-directory: . # Root directory for the artifact
